### ISSUE TITLE
add clang, clang-tools, and other pins to recipe

### ISSUE THREAD

**Issue by beckermr** [conda-forge/llvmdev-feedstock#141]
Our repodata patches keep adding the following to new releases:

```
linux-64::llvm-13.0.1-h32600fe_0.tar.bz2
-    "llvmdev   13.0.1"
+    "llvmdev   13.0.1",
+    "clang 13.0.1.*",
+    "clang-tools 13.0.1.*",
+    "llvm-tools 13.0.1.*"
linux-64::llvm-tools-13.0.1-hf817b99_0.tar.bz2
-    "llvmdev   13.0.1"
+    "llvmdev   13.0.1",
+    "clang 13.0.1.*",
+    "clang-tools 13.0.1.*",
+    "llvm 13.0.1.*"
linux-64::llvmdev-13.0.1-hf817b99_0.tar.bz2
-  "version": "13.0.1"
+  "version": "13.0.1",
+  "constrains": [
+    "clang 13.0.1.*",
+    "clang-tools 13.0.1.*",
+    "llvm 13.0.1.*",
+    "llvm-tools 13.0.1.*"
+  ]
```

I propose we either timebox the patches or add those pins here. 

Thoughts?

xref: https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/issues/223

**Comment by h-vetinari** [comment]
@jakirkham notified me in https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/issues/223

I had seen the issue but refrained from comment because I have only a shaky understanding of the problem. That said, AFAICT, the repodata patches need to be timeboxed.

Otherwise, if we added (e.g.) [clang-tools](https://github.com/conda-forge/clangdev-feedstock/blob/master/recipe/meta.yaml#L371) as a dependency here, we'd be creating a circular graph that'd be _much_ harder to bootstrap.

**Comment by beckermr** [comment]
These are run constraints, not run dependencies.

**Comment by beckermr** [comment]
Yes I think it is. The diff doesn't say explicitly. We should download the repodata and double check.

**Comment by beckermr** [comment]
See the code here: https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/blob/master/recipe/gen_patch_json.py

It appears the patches do two things. First, they relax exact pins in some cases and second, they add constrains entries.

**Comment by h-vetinari** [comment]
> The exact pin relaxing is above the section I pointed to.

You didn't include a line number, but I'm guessing you mean
https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/blob/master/recipe/gen_patch_json.py#L918
and
https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/blob/master/recipe/gen_patch_json.py#L941
?

I can't see how the first still applies - `any(dep.startswith(llvm) for dep in deps)` should always be false for `llvm in ["libllvm8", "libllvm9"]`, since we're way past llvm 8 & 9 these days...?

However, I think I get the second one now. I'll open a PR.
