### ISSUE TITLE
LLVM Polly Support

### ISSUE THREAD

**Issue by lukastruemper** [conda-forge/llvmdev-feedstock#224]
### Comment:

Hello,

I would be interested in using LLVM Polly as a dependency in an LLVM-based project. Would it be possible to also build and distribute Polly with this package?

Thanks,
Lukas

**Comment by h-vetinari** [comment]
So, this feedstock is already pushing hard against the 6h limit imposed by azure, so that builds occasionally time out.

But luckily, Polly is a top-level subproject in llvm and from a quick glance at the `CMakeLists.txt`, it supports standalone builds. So I suggest to open a PR to conda-forge/staged-recipes that just builds Polly on top of whatever other llvm bits we already have.

**Comment by lukastruemper** [comment]
I see. Yes, this is also an option. Thanks!

**Comment by jakirkham** [comment]
FWIW here's the issue to package LLVM Polly ( https://github.com/conda-forge/staged-recipes/issues/6460 )

**Comment by lukastruemper** [comment]
FYI https://github.com/conda-forge/staged-recipes/pull/22862

Have little experience in building for different platforms, so left out osx and win for now.

osx:
- {{ cxx-compiler }} -> clang 15.0.4 depends llvm-tools 15.0.4
- polly 16.0.4. -> llvmdev 16.0.4. depends llvm-tools 16.0.4

Maybe polly can depend on a subset of llvmdev and not llvm-tools implicitly
